spring:
  application:
    name: ticketing-project-microservice
  profiles:
    active: default

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://host.docker.internal:5435/ticketing-app
    username: postgres
    password: 1109
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
server:
  port: 9090
